#!/usr/bin/env python3
"""Auditable accepted-submission -> dev feedback -> freeze controller."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
import uuid
import time
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

try:
    from ..candidate_adapter import build_candidate
    from ..protocol import (
        DEV_CASES,
        HIDDEN_CASES,
        canonical_json,
        file_sha256,
        make_tree_read_only,
        materialize_external_symlinks,
        tree_digest,
        utc_now,
        validate_internal_symlinks,
        write_json,
    )
    from .dynamic_case_service import issue
    from .fixture_service import runtime_case_paths
    from .hidden_controller import run_hidden_suite
    from .lower_agent_launcher import run_case
except ImportError:
    from agentloop.candidate_adapter import build_candidate
    from agentloop.protocol import (
        DEV_CASES, HIDDEN_CASES, canonical_json, file_sha256, make_tree_read_only,
        materialize_external_symlinks, tree_digest, utc_now,
        validate_internal_symlinks, write_json,
    )
    from agentloop.evaluator.dynamic_case_service import issue
    from agentloop.evaluator.fixture_service import runtime_case_paths
    from agentloop.evaluator.hidden_controller import run_hidden_suite
    from agentloop.evaluator.lower_agent_launcher import run_case


class Controller:
    """Finite, single Builder-session lifecycle.

    The controller does not claim to observe a remote Builder's private
    conversation.  It records the evaluator-visible session id and binds every
    later submission to the feedback digest generated by the latest accepted
    dev round.  A caller integrating a real Builder must keep this id stable
    across the whole session.
    """

    def __init__(
        self,
        source: Path,
        cases: Path,
        run_dir: Path,
        broker_endpoint: str,
        builder_session_id: str | None = None,
        hidden_credential_file: Path | None = None,
        hidden_upstream: str = "https://api.deepseek.com",
        dev_cases: tuple[str, ...] = DEV_CASES,
        hidden_cases: tuple[str, ...] = HIDDEN_CASES,
        pilot_not_formal: bool = False,
        max_dev_rounds: int = 10,
        result_judge_endpoint: str | None = None,
        readiness_profile: str | None = None,
        current_binding: dict[str, Any] | None = None,
    ) -> None:
        self.source = source
        self.cases = cases
        self.run_dir = run_dir
        self.broker_endpoint = broker_endpoint
        self.result_judge_endpoint = result_judge_endpoint
        self.hidden_credential_file = hidden_credential_file.resolve() if hidden_credential_file else None
        self.hidden_upstream = hidden_upstream
        if not dev_cases or any(case_id not in DEV_CASES for case_id in dev_cases):
            raise ValueError("dev_cases must be a non-empty subset of DEV_CASES")
        if not hidden_cases or any(case_id not in HIDDEN_CASES for case_id in hidden_cases):
            raise ValueError("hidden_cases must be a non-empty subset of HIDDEN_CASES")
        if (tuple(dev_cases) != DEV_CASES or tuple(hidden_cases) != HIDDEN_CASES) and not pilot_not_formal:
            raise ValueError("reduced inventories require pilot_not_formal")
        self.dev_cases = tuple(dev_cases)
        self.hidden_cases = tuple(hidden_cases)
        self.pilot_not_formal = bool(pilot_not_formal)
        self.readiness_profile = readiness_profile
        self.current_binding = current_binding
        if readiness_profile is not None:
            if readiness_profile != "single-dev-two-round-hidden-smoke-v1":
                raise ValueError("unknown readiness profile")
            if not pilot_not_formal or tuple(dev_cases) != ("dev_001",) or tuple(hidden_cases) != ("test_001",):
                raise ValueError("readiness requires pilot dev_001 and test_001 only")
            if builder_session_id is None or max_dev_rounds != 2:
                raise ValueError("readiness requires a native session and exactly two accepted rounds")
            if not isinstance(current_binding, dict) or current_binding.get('task') != 'openwiki' or any(
                not isinstance(current_binding.get(key), str) or len(current_binding[key]) != 64
                or any(c not in '0123456789abcdef' for c in current_binding[key])
                for key in ('source_digest', 'contract_digest', 'registry_digest')):
                raise ValueError('readiness requires coordinator current source/contract/registry binding')
        if not 1 <= max_dev_rounds <= 10:
            raise ValueError("max_dev_rounds must be in 1..10")
        self.max_dev_rounds = max_dev_rounds
        self.require_builder_metadata = builder_session_id is not None
        self.builder_session_id = builder_session_id or f"builder-{uuid.uuid4().hex}"
        self.records: list[dict[str, Any]] = []
        self.frozen: dict[str, Any] | None = None
        from agentloop.evaluator.product_attempts import ProductAttempts
        state_path=self.run_dir/'controller_state.json'
        ledger_existed=(self.run_dir/'product_attempts').exists()
        self.legacy_execution_read_only=False
        if state_path.exists():
            if state_path.is_symlink():raise ValueError('controller state symlink')
            saved=json.loads(state_path.read_text())
            if saved.get('readiness_profile') != readiness_profile:
                raise ValueError('readiness profile cannot change on retained state')
            if saved.get('current_binding') != current_binding:
                raise ValueError('current binding cannot change on retained state')
            if builder_session_id not in (None,'pending-native-thread-evidence',saved.get('builder_session_id')):
                raise ValueError('restarted controller must retain the original Builder session')
            self.builder_session_id=saved['builder_session_id']
            self.records=saved['records'];self.frozen=saved.get('frozen')
            self.require_builder_metadata=saved.get('require_builder_metadata',self.require_builder_metadata)
            self.legacy_execution_read_only=saved.get('product_execution_guard')!='openwiki-product-no-replay/v1'
        elif ((ledger_existed and any((self.run_dir/'product_attempts').iterdir())) or
              any(self.run_dir.glob('candidate_*')) or (self.run_dir/'non_consuming_attempts').exists()):
            self.legacy_execution_read_only=True
        self.product_attempts=ProductAttempts(self.run_dir/'product_attempts')
        self.active_product_source_digest=None

    def _case_root(self, case_id: str) -> Path:
        group = "dev_cases" if case_id.startswith("dev_") else "test_cases"
        root = self.cases / group
        if (root / case_id).is_dir():
            return root
        if (self.cases / case_id).is_dir():
            return self.cases
        raise FileNotFoundError(f"case root missing for {case_id}: {self.cases}")

    def _case_template(self, case_id: str) -> dict[str, Any]:
        templates = json.loads(
            (Path(__file__).resolve().parent / "case_templates.json").read_text(encoding="utf-8")
        )
        value = templates.get(case_id)
        if not isinstance(value, dict):
            raise KeyError(f"missing evaluator case template: {case_id}")
        return value

    def _issue(self, case_id: str, request_root: Path) -> dict[str, Any]:
        case_input = self._case_root(case_id) / case_id / "input.md"
        task = case_input.read_text(encoding="utf-8") if case_input.is_file() else None
        return issue(
            case_id,
            self._case_template(case_id),
            request_root / "evaluator",
            request_root / "candidate",
            task,
        )

    def _evaluate_dev(self, repository: Path, round_no: int) -> dict[str, dict[str, Any]]:
        if not self.result_judge_endpoint:
            raise RuntimeError('semantic Result judge must be preflighted before public lower execution')
        from agentloop.evaluator.execution_evidence import prepare_evidence
        shared = Path('@@AGENTSWE_EDITING_CONTROL@@')
        sys.path.insert(0, str(shared))
        from execution_scoring import judge_execution_case
        results: dict[str, dict[str, Any]] = {}
        request_root = self.active_attempt / 'requests'
        output_root = self.active_attempt / 'dev'
        candidate_digest = tree_digest(repository)
        for case_id in self.dev_cases:
            case_setup_started = time.monotonic()
            issued = self._issue(case_id, request_root)
            runtime = runtime_case_paths(
                case_id, self._case_root(case_id), output_root / case_id / "fixture"
            )
            try:
                run = run_case(
                    repository,
                    Path(issued["candidate_request"]),
                    output_root / case_id,
                    self.broker_endpoint,
                    working_directory=Path(runtime["repository"]),
                    fixture_case_id=case_id,fixture_cases_root=self._case_root(case_id),fixture_output=output_root/case_id/"fixture",
                    case_setup_started=case_setup_started,
                )
            except Exception as exc:  # preserve a suite-level evaluator record
                run = {
                    "valid": False,
                    "classification": "evaluator_failure",
                    "error": f"{type(exc).__name__}: {exc}",
                    "product_started": False,
                    "infrastructure_invalid": True,
                }
                write_json(output_root / case_id / "launcher_result.json", run)
            record = prepare_evidence(run, case_id=case_id, candidate_digest=candidate_digest,
                repository=repository,
                output=output_root / case_id, request=issued['candidate_request'],
                cases_root=self._case_root(case_id), initial=runtime['repository'])
            cap_contract = None
            if self.readiness_profile:
                from execution_contract import classify_candidate_execution
                verdict = classify_candidate_execution(record, case_id=case_id,
                    candidate_digest=candidate_digest)
                judgement = {'classification': verdict['classification'],
                    'contract_valid': verdict['classification'] in {'scoreable', 'candidate_zero'},
                    'score': None, 'assessment': verdict.get('reason'),
                    'evaluation_mode': 'readiness_public_execution', 'judge_invoked': False}
                write_json(output_root / case_id / 'readiness_execution_classification.json', judgement)
            else:
                cap_contract = self._dev_score_caps(case_id, record, output_root / case_id)
                judgement = judge_execution_case(case_input=Path(record['executed_task_path']),
                    rubric=Path(__file__).parent / 'result_rubric.md',
                    artifact=Path(record['artifact_validation']['artifact_path']),
                    raw_trajectory=Path(record['observed_trajectory_path']),
                    native_evidence=output_root / case_id / 'launcher_result.json',
                    private_oracle=Path(record['private_oracle_comparison_path']),
                    execution_record=record, candidate_digest=candidate_digest, case_id=case_id,
                    output=output_root / case_id / 'semantic_result', broker_endpoint=self.result_judge_endpoint,
                    score_cap_contract=cap_contract)
            results[case_id] = {
                "issued": issued,
                "runtime": {
                    "repository": str(runtime["repository"]),
                    "manifest": str(runtime["manifest"]),
                    "change_source_kind": runtime["change_source_kind"],
                },
                "run": run,
                "classification": judgement.get('classification'),
                "infrastructure_invalid": not judgement.get('contract_valid'),
                "execution": record, "judgement": judgement,
                "score_caps": self._score_caps_summary(cap_contract, judgement),
            }
            if self.active_product_source_digest:
                self.product_attempts.record_case(self.active_product_source_digest,case_id,
                    results[case_id],output_root/case_id)
        return results

    @staticmethod
    def _dev_score_caps(case_id: str, record: dict[str, Any], case_output: Path):
        """Issue for a dev case the same evidence-bound ceilings the formal axis issues.

        0921: `evaluator/result_score_caps.py` ran only from `evaluator/formal_axes.py`,
        so the hidden cases were capped and the dev cases were not.  The 0920 run ended
        with the Builder reading 74/75 on dev while the formal Result axis gave 14.0 for
        the same behaviour, which told it to stop working on exactly the surface-family
        coverage that binds the real score.  The contract is built from the same
        evaluator-computed evidence and binds the same rubric / native-evidence /
        oracle bytes the judge is handed.  It never fails a dev round: on any problem
        the dev case is judged exactly as before, without a ceiling.
        """
        import runpy
        try:
            destination = Path(case_output) / 'result_score_caps.json'
            # Per-submission immutability: the contract is a judge input that
            # `execution_scoring.judge_execution_case` seals by sha256 into
            # `scoring_intent.json`.  Issue it exactly once per submission and never
            # rewrite it, so a resumed controller cannot move the ceiling a round was
            # already judged under (a rewrite would surface as
            # "scoring directory already belongs to different immutable inputs").
            if destination.is_symlink():
                return None
            if destination.is_file():
                return destination
            impl = Path(__file__).resolve().parents[2] / 'evaluator' / 'result_score_caps.py'
            caps = runpy.run_path(str(impl))
            staged = destination.with_name(destination.name + '.issuing')
            if staged.exists():
                staged.unlink()
            caps['write_contract'](staged, case_id=case_id,
                rubric=Path(__file__).parent / 'result_rubric.md',
                native_evidence=Path(case_output) / 'launcher_result.json',
                oracle_summary=Path(record['private_oracle_comparison_path']),
                execution_record=Path(record['execution_record_path']))
            os.link(staged, destination)  # create-only; raises if it already exists
            staged.unlink()
            return destination if destination.is_file() else None
        except Exception:  # noqa: BLE001 - a ceiling never fails a dev round
            return None

    @staticmethod
    def _score_caps_summary(cap_contract, judgement: dict[str, Any]) -> dict[str, Any]:
        """Summarise, for Builder feedback, the ceilings the dev judge was bound to.

        0921: the contract reached the dev judge but never reached the Builder, so a dev
        round could report 74/100 and 75/100 for behaviour whose determinate ceilings said
        24 and 20 and whose formal Result axis scored 14.0 (`0920-fh-002`, round 5).  Only
        evaluator-computed, already-published material crosses: the cap id, the binding
        maximum and the reason text.  Evidence references are deliberately not rendered
        (they are evaluator paths), and no hidden case content or private oracle
        expectation is carried.  It never fails a round: on any problem the summary is
        empty and feedback reads exactly as before.
        """
        summary: dict[str, Any] = {'contract_issued': cap_contract is not None,
            'effective_ceiling': None, 'judge_score_cap': None,
            'violated_caps': [], 'semantic_review_violated': []}
        entries: list[Any] = []
        try:
            if cap_contract is not None:
                value = json.loads(Path(cap_contract).read_text(encoding='utf-8'))
                entries = value.get('entries') if isinstance(value.get('entries'), list) else []
        except (OSError, ValueError, TypeError):
            entries = []
        applied: list[int] = []
        published: dict[Any, dict[str, Any]] = {}
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            published[entry.get('cap_id')] = entry
            if entry.get('status') == 'violated':
                summary['violated_caps'].append({'cap_id': entry.get('cap_id'),
                    'maximum_score': entry.get('maximum_score'), 'reason': entry.get('reason')})
                if type(entry.get('maximum_score')) is int:
                    applied.append(entry['maximum_score'])
        summary['effective_ceiling'] = min(applied) if applied else None
        try:
            contract = json.loads(Path(judgement.get('contract_path')).read_text(encoding='utf-8'))
        except (OSError, ValueError, TypeError):
            contract = {}
        if type(contract.get('score_cap')) is int:
            summary['judge_score_cap'] = contract['score_cap']
        assessments = contract.get('ceiling_assessments')
        if isinstance(assessments, dict):
            for cap_id, item in sorted(assessments.items()):
                if isinstance(item, dict) and item.get('violated') is True:
                    entry = published.get(cap_id) or {}
                    summary['semantic_review_violated'].append({'cap_id': cap_id,
                        'maximum_score': entry.get('maximum_score'),
                        'reason': item.get('evidence') or entry.get('reason')})
        return summary

    @staticmethod
    def _case_feedback_errors(item: dict[str, Any]) -> dict[str, list[str]]:
        """Verbatim harness and validator errors for one dev case.

        Create's dev feedback hands the Builder every harness_error and major_error
        verbatim (`one_stop.py: feedback_text`); Edit's dev feedback carried the score
        and the assessment only, so a Builder could not tell a killed process from a
        rejected artifact.  Evaluator host paths are scrubbed by `public_text` when the
        payload is rendered.
        """
        run = item.get('run') or {}
        execution = item.get('execution') or {}
        validation = execution.get('artifact_validation') or {}
        judgement = item.get('judgement') or {}
        harness: list[str] = []
        validator: list[str] = []

        def add(bucket: list[str], value: Any) -> None:
            text = str(value).strip()
            if text and text not in bucket:
                bucket.append(text)

        for value in (run.get('error'), run.get('failure'), execution.get('error')):
            if isinstance(value, str):
                add(harness, value)
        for value in run.get('transport_errors') or []:
            add(harness, value)
        attribution = execution.get('failure_attribution') or {}
        if isinstance(attribution.get('reason'), str):
            add(harness, attribution['reason'])
        if (isinstance(judgement.get('reason'), str)
                and judgement.get('classification') != 'scoreable'):
            add(harness, judgement['reason'])
        for value in validation.get('errors') or []:
            add(validator, value)
        for value in validation.get('quality_findings') or []:
            add(validator, value)
        try:
            contract = json.loads(Path(judgement.get('contract_path')).read_text(encoding='utf-8'))
        except (OSError, ValueError, TypeError):
            contract = {}
        for value in contract.get('errors') or []:
            add(validator, value)
        return {'harness_errors': harness, 'validator_errors': validator}

    @staticmethod
    def _feedback_payload(record: dict[str, Any]) -> dict[str, Any]:
        from agentloop.evaluator.public_feedback import public_payload
        return public_payload({
            "schema_version": "openwiki-agentloop-feedback/v1",
            "round": record["round"],
            "builder_session_id": record["builder_session_id"],
            "candidate_digest": record["candidate_digest"],
            "cases": {
                case_id: {
                    "classification": item.get("classification"),
                    "valid": item.get("run", {}).get("valid", False),
                    "infrastructure_invalid": item.get("infrastructure_invalid", False),
                    "broker_delta": item.get("run", {}).get("broker_delta", {}),
                    "result_score": item.get('judgement', {}).get('score'),
                    "semantic_contract_valid": item.get('judgement', {}).get('contract_valid'),
                    "assessment": item.get('judgement', {}).get('assessment'),
                    "major_errors": item.get('judgement', {}).get('major_errors'),
                    "dimensions": item.get('judgement', {}).get('dimensions'),
                    # 0921: the same contract the hidden path issues, and the same
                    # harness/validator text Create's dev feedback carries.
                    "round_consumed": bool(item.get('judgement', {}).get('round_consumed')),
                    "reason": item.get('judgement', {}).get('reason'),
                    "score_caps": item.get('score_caps'),
                    **Controller._case_feedback_errors(item),
                    "candidate_observation": {
                        'exit_code': item.get('run', {}).get('exit_code'),
                        'artifact_present': item.get('execution', {}).get('artifact_validation', {}).get('present'),
                        'errors': item.get('execution', {}).get('artifact_validation', {}).get('errors', []),
                        'quality_findings': item.get('execution', {}).get('artifact_validation', {}).get('quality_findings', []),
                        'error': item.get('run', {}).get('error'),
                        'stderr_tail': item.get('run', {}).get('stderr_tail'),
                    } if item.get('judgement', {}).get('evaluation_mode') == 'readiness_public_execution' else None,
                }
                for case_id, item in record["dev_cases"].items()
            },
        })

    def _write_feedback(self, record: dict[str, Any]) -> dict[str, Any]:
        payload = self._feedback_payload(record)
        digest = hashlib.sha256(canonical_json(payload)).hexdigest()
        payload["feedback_digest"] = digest
        feedback_dir = Path(record['attempt_path'])
        write_json(feedback_dir / "feedback.json", payload)
        lines = [
            f"# OpenWiki lower-agent dev feedback — Candidate {record['round']}",
            "",
            f"- builder_session_id: `{record['builder_session_id']}`",
            f"- candidate_digest: `{record['candidate_digest']}`",
            f"- feedback_digest: `{digest}`",
            "",
        ]
        from agentloop.evaluator.public_feedback import public_text

        def _cap_line(items):
            return "; ".join(
                "%s (<=%s): %s" % (entry.get('cap_id'), entry.get('maximum_score'),
                                   public_text(str(entry.get('reason'))))
                for entry in items or []) or "none"

        for case_id, item in record["dev_cases"].items():
            run = item.get("run", {})
            judgement = item.get("judgement", {}) or {}
            caps = item.get("score_caps") or {}
            errors = self._case_feedback_errors(item)
            # 0921: render the flag the attempt is actually voided on.  `submit()` voids
            # from the judged verdict (`not judgement['contract_valid']`), while this
            # block printed the launcher's own `infrastructure_invalid`.  On 0921-v4-001
            # the Builder read `candidate_timeout` / `infrastructure invalid: False` for
            # three attempts that were in fact voided as `unresolved`, and had nothing to
            # act on.
            verdict_infrastructure = (bool(item.get("infrastructure_invalid"))
                                      or not judgement.get("contract_valid"))
            lines.extend(
                [
                    f"## {case_id}",
                    f"- classification: `{judgement.get('classification', 'unclassified')}`",
                    f"- infrastructure invalid: `{verdict_infrastructure}`",
                    f"- round consumed: `{bool(judgement.get('round_consumed'))}`",
                    f"- verdict reason: {public_text(str(judgement.get('reason')))}",
                    f"- observed execution: `{run.get('classification', 'unclassified')}`"
                    f" (candidate behaviour `{run.get('candidate_classification', 'N/A')}`)",
                    f"- broker delta: `{json.dumps(run.get('broker_delta', {}), sort_keys=True)}`",
                    f"- semantic Result score: {judgement.get('score')}",
                    "- evidenced Result ceiling: "
                    + (str(caps.get('effective_ceiling')) if caps.get('contract_issued') else 'contract not issued')
                    + f" (ceiling the judge was bound to: {caps.get('judge_score_cap')})",
                    "- violated ceilings: " + _cap_line(caps.get('violated_caps')),
                    "- ceilings the judge established as violated: "
                    + _cap_line(caps.get('semantic_review_violated')),
                    f"- assessment: {judgement.get('assessment')}",
                    f"- major errors: {judgement.get('major_errors')}",
                    "- harness errors: "
                    + ("; ".join(public_text(text) for text in errors['harness_errors']) or "none"),
                    "- validator errors: "
                    + ("; ".join(public_text(text) for text in errors['validator_errors']) or "none"),
                    f"- artifact contract findings: {item.get('execution', {}).get('artifact_validation', {}).get('quality_findings', [])}",
                    f"- evaluator note: {'the product made NO model call through the evaluator broker (broker delta calls=0); a result authored without the model has no native authorship and scores 0 -- the case must be performed through model calls (OPENAI_BASE_URL / --modelId)' if not (run.get('broker_delta') or {}).get('calls') else 'model calls observed through the evaluator broker'}",
                    "",
                ]
            )
        path = feedback_dir / "feedback.md"
        path.write_text("\n".join(lines), encoding="utf-8")
        return {"available": True, "feedback_digest": digest, "json": str(feedback_dir / "feedback.json"), "markdown": str(path)}

    def _builder_metadata(
        self,
        candidate: Path,
        round_no: int,
        parent_digest: str | None,
        feedback_digest: str | None,
    ) -> dict[str, Any]:
        path = candidate / "run_report.json"
        if not self.require_builder_metadata:
            return {"required": False, "valid": True, "path": str(path)}
        try:
            value = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError) as exc:
            return {"required": True, "valid": False, "errors": [f"run_report.json: {type(exc).__name__}: {exc}"]}
        if not isinstance(value, dict):
            return {"required": True, "valid": False, "errors": ["run_report.json must be an object"]}
        errors: list[str] = []
        if value.get("builder_session_id") != self.builder_session_id:
            errors.append("builder_session_id does not match controller session")
        if value.get("submission_number") != round_no:
            errors.append(f"submission_number must be {round_no}")
        if self.readiness_profile and round_no == 1:
            for key in ('revision_of_candidate_digest', 'feedback_digest'):
                if key not in value or value[key] is not None:
                    errors.append('first readiness submission requires explicit null ' + key)
        if round_no >= 2:
            if value.get("revision_of_candidate_digest") != parent_digest:
                errors.append("revision_of_candidate_digest does not match the latest accepted submission")
            if value.get("feedback_digest") != feedback_digest:
                errors.append("feedback_digest does not match evaluator feedback")
            if self.readiness_profile:
                try:
                    report = json.loads((candidate / 'edit_report.json').read_bytes())
                    if not isinstance(report.get('feedback_response'), str) or not report['feedback_response'].strip():
                        errors.append('edit_report.feedback_response must explain the revision')
                    previous = Path(self.records[-1]['candidate_path']) / 'solution.patch'
                    if file_sha256(candidate / 'solution.patch') == file_sha256(previous):
                        errors.append('readiness revision must change solution.patch, not reports alone')
                except (OSError, ValueError, KeyError, TypeError) as exc:
                    errors.append('readiness revision evidence unavailable: ' + str(exc))
        return {
            "required": True,
            "valid": not errors,
            "errors": errors,
            "path": str(path),
            "builder_session_id": value.get("builder_session_id"),
            "submission_number": value.get("submission_number"),
        }

    def duplicate_submission(self, candidate: Path) -> dict[str, Any] | None:
        """Return the original accepted result for an exact Candidate replay.

        Duplicate detection deliberately precedes the freeze fence, round
        bounds, Builder metadata validation, builds, and dev evaluation.  A
        replay is an acknowledgement of an already accepted capability round,
        not a new attempt at the next round.
        """
        digest = tree_digest(candidate)
        original = next(
            (item for item in self.records if item["candidate_digest"] == digest),
            None,
        )
        if original is None:
            return None
        feedback = original.get("feedback", {})
        return {
            "schema_version": "openwiki-agentloop-duplicate-submission-v1",
            "round": original["round"],
            "accepted_round": original["round"],
            "builder_session_id": original["builder_session_id"],
            "candidate_digest": digest,
            "feedback": feedback,
            "feedback_digest": feedback.get("feedback_digest"),
            "consumed": False,
            "submission_consumed": False,
            "consumes_capability_round": False,
            "idempotent": True,
        }

    def submit(self, candidate: Path, round_no: int, evaluate_dev: bool = True) -> dict[str, Any]:
        if self.readiness_profile and not evaluate_dev:
            raise ValueError('readiness rounds require actual public execution')
        duplicate = self.duplicate_submission(candidate)
        if duplicate is not None:
            return duplicate
        if self.legacy_execution_read_only:
            raise RuntimeError('legacy public execution is read-only; retained results cannot be resampled')
        if self.frozen is not None:
            raise RuntimeError("controller is already frozen")
        digest = tree_digest(candidate)
        if not 1 <= round_no <= self.max_dev_rounds:
            raise ValueError(f"accepted submission number must be in 1..{self.max_dev_rounds}")
        if round_no != len(self.records) + 1:
            raise RuntimeError("accepted submissions must be submitted in order")
        parent_digest = self.records[-1]["candidate_digest"] if round_no >= 2 else None
        expected_feedback = self.records[-1].get("feedback", {}).get("feedback_digest") if round_no >= 2 else None
        builder_metadata = self._builder_metadata(candidate, round_no, parent_digest, expected_feedback)

        def non_consuming(record: dict[str, Any], reason: str) -> dict[str, Any]:
            """Archive a failed preflight without burning an accepted slot."""
            record["consumed"] = False
            record["submission_consumed"] = False
            record["consumes_capability_round"] = False
            record["retry_same_round"] = not bool(record.get('product_source_digest'))
            record['retry_allowed']=record['retry_same_round']
            record["non_consuming_reason"] = reason
            attempts = self.run_dir / "non_consuming_attempts"
            attempts.mkdir(parents=True, exist_ok=True)
            attempt_id = len(list(attempts.glob("attempt_*.json"))) + 1
            write_json(attempts / f"attempt_{attempt_id:03d}.json", record)
            return record

        build_dir = self.run_dir / f"candidate_{round_no}_attempt_{uuid.uuid4().hex[:12]}"
        self.active_attempt = build_dir
        if not builder_metadata.get("valid"):
            return non_consuming({
                "round": round_no,
                "role": "initial" if round_no == 1 else "feedback_revision",
                "builder_session_id": self.builder_session_id,
                "candidate_digest": digest,
                "build": {
                    "valid": False,
                    "classification": "candidate_session_contract_failure",
                    "errors": builder_metadata.get("errors", []),
                },
                "builder_metadata": builder_metadata,
                "dev_cases": {},
                "feedback": {"available": False},
                "revision": {
                    "parent_candidate_digest": parent_digest,
                    "feedback_digest": expected_feedback,
                    "same_builder_session": round_no == 1 or self.records[-1].get("builder_session_id") == self.builder_session_id,
                    "feedback_bound_submission": False,
                },
            }, "builder_session_contract_preflight")

        # F6 (2026-09-19): this snapshot used to be readiness-only, so in a
        # formal run record['candidate_path'] stayed the Builder-writable
        # workspace directory that the next round overwrites -- the recorded
        # candidate_digest then no longer described the directory it named, and
        # the evidence anchor was mutable for the life of the Builder session.
        # Nothing on the formal path writes through candidate_path, and the
        # freeze materialises from build["product_entry"], not from here.
        snapshot = build_dir / 'submission'
        shutil.copytree(candidate, snapshot, symlinks=True)
        if tree_digest(snapshot) != digest:
            raise RuntimeError('submission changed while snapshotting')
        make_tree_read_only(snapshot)
        candidate = snapshot
        build = build_candidate(self.source, candidate, build_dir, run_build=True,
            readiness_profile=self.readiness_profile)
        record: dict[str, Any] = {
            "attempt_path": str(build_dir),
            "candidate_path": str(candidate),
            "round": round_no,
            "role": "initial" if round_no == 1 else "feedback_revision",
            "builder_session_id": self.builder_session_id,
            "candidate_digest": digest,
            "build": build,
            "builder_metadata": builder_metadata,
            "dev_cases": {},
            "feedback": {"available": False},
            "revision": {
                "parent_candidate_digest": parent_digest,
                "feedback_digest": expected_feedback,
                "same_builder_session": round_no == 1 or self.records[-1].get("builder_session_id") == self.builder_session_id,
                "feedback_bound_submission": builder_metadata.get("valid") is True if round_no >= 2 else True,
            },
        }
        if not build.get("valid"):
            record["feedback"] = {
                "available": False,
                "classification": build.get("classification", "candidate_build_failure"),
            }
            return non_consuming(record, "candidate_materialization_or_build_preflight")
        if build.get("valid") and evaluate_dev:
            repository = Path(build["product_entry"]).parent.parent
            try:product=self.checked_product_identity(build,build_dir)
            except (ValueError,KeyError,OSError,TypeError) as exc:
                record['build']={**build,'valid':False,'classification':'infrastructure_failure',
                    'failure':'owned build did not establish stable product source identity', 'errors':[str(exc)]}
                return non_consuming(record,'product_identity_preflight')
            record['product_source_digest']=product
            prior=self.product_attempts.lookup(product)
            if prior is not None:return self.product_replay_record(prior,record)
            from agentloop.evaluator.product_attempts import ProductReplayBlocked
            try:
                self.product_attempts.claim(product,{'builder_session_id':self.builder_session_id,
                    'round':round_no,'delivery_digest':digest,'dev_cases':list(self.dev_cases),
                    'attempt_path':str(build_dir),
                    'product_source_identity_path':build['product_source_identity_path'],
                    'product_source_identity_sha256':build['product_source_identity_sha256']})
            except ProductReplayBlocked:
                return self.product_replay_record(self.product_attempts.lookup(product),record)
            # Session/state survives the first infrastructure-invalid attempt.
            # A crash between claim and this write leaves a read-only run.
            self._write_state()
            self.active_product_source_digest=product
            try:
                record["dev_cases"] = self._evaluate_dev(repository, round_no)
                for case_id,value in record['dev_cases'].items():
                    self.product_attempts.record_case(product,case_id,value,build_dir/'dev'/case_id)
            except Exception as exc:
                prior=self.product_attempts.lookup(product)
                record['dev_cases']=(prior or {}).get('case_results',{})
                record['error']=type(exc).__name__+': '+str(exc)
                record['feedback']=self._write_feedback(record)
                record['feedback']['infrastructure_invalid']=True
                record=non_consuming(record,'public_dev_interrupted_or_unknown')
                self.product_attempts.finish(product,record)
                return record
            finally:
                self.active_product_source_digest=None
            record["feedback"] = self._write_feedback(record)
            record["feedback"]["infrastructure_invalid"] = any(
                bool(item.get("infrastructure_invalid")) or not item.get('judgement', {}).get('contract_valid')
                for item in record["dev_cases"].values()
            )
            if record["feedback"]["infrastructure_invalid"]:
                record=non_consuming(record, "public_dev_infrastructure_preflight")
                self.product_attempts.finish(product,record)
                return record
        record["consumed"] = True
        record["submission_consumed"] = True
        record["consumes_capability_round"] = True
        if not post_freeze_superseded(self, record):
            self.records.append(record)
        self._write_state()
        if record.get('product_source_digest'):
            self.product_attempts.finish(record['product_source_digest'],record)
        return record

    def product_replay_record(self,prior,current):
        """Expose only retained evidence; never run another dev or judge."""
        saved=(prior or {}).get('record')
        original=saved if isinstance(saved,dict) else current
        return {**original,'dev_cases':(prior or {}).get('case_results',original.get('dev_cases',{})),
            'replay_blocked':True,'classification':'product_execution_replay_blocked',
            'product_source_digest':current['product_source_digest'],
            'consumed':False,'submission_consumed':False,'consumes_capability_round':False,'idempotent':False,
            'retry_same_round':False,'retry_allowed':False,
            'non_consuming_reason':'retained_product_execution_no_replay'}

    @staticmethod
    def checked_product_identity(build,build_dir):
        """Verify the evaluator-owned pre-build identity receipt, not Git bytes."""
        path=Path(build['product_source_identity_path'])
        if path != build_dir/'product-source-identity.json' or path.is_symlink():
            raise ValueError('unexpected product source identity path')
        data=path.read_bytes()
        if hashlib.sha256(data).hexdigest()!=build['product_source_identity_sha256']:
            raise ValueError('product source identity receipt changed')
        value=json.loads(data);product=value.pop('product_source_digest')
        if value.get('schema_version')!='openwiki-product-source-identity/v1' or value.get('excluded')!=['.git']:
            raise ValueError('unrecognized product source identity algorithm')
        if hashlib.sha256(canonical_json(value)).hexdigest()!=product or product!=build['product_source_digest']:
            raise ValueError('product source identity digest mismatch')
        return product

    def _write_state(self) -> None:
        value={
                "schema_version": 2,
                "builder_session_id": self.builder_session_id,
                "records": self.records,
                "frozen": self.frozen,
                'require_builder_metadata':self.require_builder_metadata,
                'product_execution_guard':'openwiki-product-no-replay/v1',
                'readiness_profile': self.readiness_profile,
                'current_binding': self.current_binding,
            }
        path=self.run_dir/'controller_state.json';temporary=path.with_suffix('.json.tmp')
        self.run_dir.mkdir(parents=True,exist_ok=True)
        with temporary.open('wb') as handle:
            handle.write(canonical_json(value));handle.flush();os.fsync(handle.fileno())
        os.replace(temporary,path)
        fd=os.open(self.run_dir,os.O_RDONLY|os.O_DIRECTORY)
        try:os.fsync(fd)
        finally:os.close(fd)

    def freeze(self, *, builder_exit_evidence: dict[str, Any] | None = None) -> dict[str, Any]:
        if self.frozen is not None or (self.run_dir / "freeze_manifest.json").exists():
            raise RuntimeError("latest accepted Candidate has already been frozen")
        if not self.records:
            raise RuntimeError("freeze requires at least one accepted submission")
        if self.readiness_profile:
            self.validate_readiness_rounds(builder_exit_evidence)
        latest = self.records[-1]
        latest_round = int(latest.get("round", len(self.records)))
        if len({item["candidate_digest"] for item in self.records}) != len(self.records):
            raise RuntimeError("accepted candidate digests must be distinct")
        for index, record in enumerate(self.records, start=1):
            label = "Candidate 1" if index == 1 else f"accepted submission {index}"
            if list(record.get("dev_cases", {})) != list(self.dev_cases):
                raise RuntimeError(f"{label} does not contain the configured public inventory")
            if not record.get("feedback", {}).get("available"):
                raise RuntimeError(f"{label} has no real dev feedback")
            if record.get("feedback", {}).get("infrastructure_invalid"):
                raise RuntimeError(f"{label} dev provider/broker evidence is invalid")
            if not record["build"].get("valid"):
                raise RuntimeError(f"cannot freeze invalid {label}")
            if index >= 2 and (
                not record["revision"].get("same_builder_session")
                or not record["revision"].get("feedback_digest")
                or not record["builder_metadata"].get("valid")
                or not record["revision"].get("feedback_bound_submission")
            ):
                raise RuntimeError(f"{label} is not bound to same-session feedback")

        source_repository = Path(latest["build"]["product_entry"]).parent.parent
        frozen_repository = self.run_dir / "frozen_candidate" / "repository"
        shutil.rmtree(frozen_repository.parent, ignore_errors=True)
        shutil.copytree(source_repository, frozen_repository, symlinks=True)
        materialize_external_symlinks(frozen_repository)
        validate_internal_symlinks(frozen_repository)
        repository_digest = tree_digest(frozen_repository)
        freeze = {
            "schema_version": 2,
            "source_submission": latest_round,
            "source_submission_id": f"candidate-{latest_round:03d}-{latest['candidate_digest'][:12]}",
            "accepted_submission_count": len(self.records),
            "max_dev_rounds": self.max_dev_rounds,
            "accepted_candidate_digests": [item["candidate_digest"] for item in self.records],
            "candidate_digest": repository_digest,
            "repository_digest": repository_digest,
            "repository_digest_algorithm": "sha256-tree-v1",
            "candidate_path": str(frozen_repository),
            # The Code judge focuses its evidence on the delivery beside the
            # accepted Candidate; without this it packs the whole repository.
            "accepted_candidate_path": str(latest["candidate_path"]),
            "builder_session_id": self.builder_session_id,
            "feedback_digest": latest["revision"].get("feedback_digest"),
            "feedback_consumed": True,
            "feedback_chain_complete": all(
                index == 1 or bool(record.get("revision", {}).get("feedback_bound_submission"))
                for index, record in enumerate(self.records, start=1)
            ),
            "frozen_at": utc_now(),
            "hidden_started_at": None,
            "hidden_allowed": True,
            "dev_evaluated": True,
            "immutable_repository": True,
            "credential_mounted_to_candidate": False,
            "hidden_case_inventory": list(self.hidden_cases),
            "pilot_not_formal": self.pilot_not_formal,
            "readiness_profile": self.readiness_profile,
            "current_binding": self.current_binding,
            "delivery_candidate_digest": latest["candidate_digest"],
            "submission_sha256": {
                name: file_sha256(Path(latest["candidate_path"]) / name)
                for name in ("solution.patch", "edit_report.json", "run_report.json")
            } if self.readiness_profile else None,
            "builder_exit_evidence": builder_exit_evidence,
        }
        make_tree_read_only(frozen_repository)
        freeze_path = self.run_dir / "freeze_manifest.json"
        write_json(freeze_path, freeze)
        seal_path = self.run_dir / "freeze_manifest.sha256"
        seal_path.write_text(file_sha256(freeze_path) + "\n", encoding="ascii")
        freeze_path.chmod(0o444)
        seal_path.chmod(0o444)
        self.frozen = freeze
        self._write_state()
        return freeze

    def validate_readiness_rounds(self, builder_exit_evidence: dict[str, Any] | None) -> None:
        if len(self.records) != 2:
            raise RuntimeError('readiness freeze requires exactly two valid public rounds')
        if not builder_exit_evidence or builder_exit_evidence.get('returncode') != 0 or builder_exit_evidence.get('native_valid') is not True:
            raise RuntimeError('readiness freeze requires successful native Builder exit')
        if builder_exit_evidence.get('builder_session_id') != self.builder_session_id:
            raise RuntimeError('Builder exit session does not match controller')
        first, second = self.records
        if first['candidate_digest'] == second['candidate_digest']:
            raise RuntimeError('readiness requires a distinct Candidate revision')
        first_submission, second_submission = Path(first['candidate_path']), Path(second['candidate_path'])
        if file_sha256(first_submission / 'solution.patch') == file_sha256(second_submission / 'solution.patch'):
            raise RuntimeError('readiness revision must change solution.patch')
        first_repository = Path(first['build']['product_entry']).parent.parent
        second_repository = Path(second['build']['product_entry']).parent.parent
        if tree_digest(first_repository) == tree_digest(second_repository):
            raise RuntimeError('readiness revision must change the materialized product')
        for record in self.records:
            if record.get('builder_session_id') != self.builder_session_id or record.get('submission_consumed') is not True:
                raise RuntimeError('readiness requires same-session accepted rounds')
            if tree_digest(Path(record['candidate_path'])) != record['candidate_digest']:
                raise RuntimeError('accepted submission bytes changed')
            stable = record['build'].get('readiness_source_immutability', {})
            repository = Path(record['build']['product_entry']).parent.parent
            if (stable.get('unchanged') is not True or stable.get('before') != stable.get('after')
                    or tree_digest(repository) != stable.get('materialized_repository_digest')):
                raise RuntimeError('accepted build source or repository changed before freeze')
            feedback = record.get('feedback', {})
            path = Path(feedback.get('json', ''))
            if path.is_symlink() or not path.resolve().is_relative_to(self.run_dir.resolve()):
                raise RuntimeError('readiness feedback escaped evaluator run')
            payload = json.loads(path.read_bytes())
            digest = hashlib.sha256(canonical_json({k: v for k, v in payload.items() if k != 'feedback_digest'})).hexdigest()
            if digest != feedback.get('feedback_digest') or digest != payload.get('feedback_digest'):
                raise RuntimeError('readiness feedback bytes changed')
        revision = second.get('revision', {})
        if revision.get('parent_candidate_digest') != first['candidate_digest'] or revision.get('feedback_digest') != first['feedback']['feedback_digest']:
            raise RuntimeError('readiness revision must consume exact first-round feedback')

    def hidden(self) -> dict[str, Any]:
        if self.frozen is None:
            raise RuntimeError("hidden evaluation is forbidden before freeze")
        if self.hidden_credential_file is None:
            raise RuntimeError("hidden evaluation requires an evaluator-owned credential file")
        result = run_hidden_suite(
            self.run_dir / "freeze_manifest.json",
            self.run_dir / "hidden-result.json",
            self.hidden_credential_file,
            self._case_root("test_001").parent,
            upstream=self.hidden_upstream,
        )
        self._write_state()
        return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--cases", type=Path, required=True)
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--broker-endpoint", default="http://127.0.0.1:18080/v1/responses")
    parser.add_argument("--hidden-credential-file", type=Path)
    parser.add_argument("--hidden-upstream", default=os.environ.get("AGENTSWE_UPSTREAM_BASE_URL", "https://api.deepseek.com"))
    parser.add_argument("--builder-session-id", required=True, help="Stable Builder session id required for a formal same-session run")
    parser.add_argument("--candidate", type=Path, action="append", help="ordered Candidate submission; repeat up to --max-dev-rounds")
    parser.add_argument("--max-dev-rounds", type=int, default=10)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        print(json.dumps({"controller": "loadable", "guards": ["same_builder_session", "feedback_digest", "immutable_repository_digest", "hidden_attestation"]}))
        return 0
    if not args.candidate:
        raise SystemExit("provide at least one --candidate")
    if not 1 <= args.max_dev_rounds <= 10:
        raise SystemExit("--max-dev-rounds must be in 1..10")
    if not args.hidden_credential_file:
        raise SystemExit("--hidden-credential-file is required for a real hidden run")
    controller = Controller(
        args.source.resolve(),
        args.cases.resolve(),
        args.run_dir.resolve(),
        args.broker_endpoint,
        args.builder_session_id,
        args.hidden_credential_file.resolve(),
        args.hidden_upstream,
        max_dev_rounds=args.max_dev_rounds,
    )
    submissions = []
    for candidate in args.candidate:
        round_no = len(controller.records) + 1
        record = controller.submit(candidate.resolve(), round_no)
        submissions.append(record)
        if record.get("idempotent") is True:
            continue
        if not record.get("submission_consumed"):
            print(json.dumps(record, indent=2, ensure_ascii=False))
            return 2
    frozen = controller.freeze()
    hidden = controller.hidden()
    print(json.dumps({"submissions": submissions, "freeze": frozen, "hidden": hidden}, indent=2, ensure_ascii=False))
    return 0 if hidden.get("formal_result_eligible") is True else 2


# --- 0921b freeze/submit race guard (harness, package 113-freeze-race) ------
# A submission admitted before the freeze (the fence is evaluated only at
# submit() entry) can still be running its dev evaluation in a
# ThreadingUnixStreamServer handler thread when the Builder process exits and
# the driver freezes the run.  The finished record was then appended to the
# accepted history minutes after the seal, so the sealed freeze no longer
# matched the controller history and the finalizer refused the cell.
# Two guards, both no-ops when nothing is in flight:
#   1. every freeze entry point first waits for accepted submissions that are
#      still being evaluated in OTHER threads (bounded by
#      AGENTSWE_FREEZE_QUIESCE_SECONDS, default 45 min), so the seal describes
#      the true last accepted round;
#   2. the accepted history refuses a record once the run is sealed; the
#      finished evaluation is archived under post_freeze_attempts/ as a
#      superseded post-freeze completion instead of contradicting the seal.
import functools as _fr_functools
import inspect as _fr_inspect
import json as _fr_json
import os as _fr_os
import threading as _fr_threading
import time as _fr_time
from pathlib import Path as _FrPath

_FR_CV = _fr_threading.Condition()
_FR_INFLIGHT = {}
_FR_CAP_DEFAULT = 2700.0
_FR_FREEZE_METHODS = ('freeze', 'freeze_latest', 'freeze_candidate_2',
                      'freeze_on_builder_exit', '_freeze')


def _fr_cap():
    raw = _fr_os.environ.get('AGENTSWE_FREEZE_QUIESCE_SECONDS')
    try:
        value = float(raw) if raw else _FR_CAP_DEFAULT
    except (TypeError, ValueError):
        return _FR_CAP_DEFAULT
    return value if value > 0 else _FR_CAP_DEFAULT


def _fr_begin():
    ident = _fr_threading.get_ident()
    with _FR_CV:
        _FR_INFLIGHT[ident] = _FR_INFLIGHT.get(ident, 0) + 1


def _fr_end():
    ident = _fr_threading.get_ident()
    with _FR_CV:
        remaining = _FR_INFLIGHT.get(ident, 0) - 1
        if remaining > 0:
            _FR_INFLIGHT[ident] = remaining
        else:
            _FR_INFLIGHT.pop(ident, None)
        _FR_CV.notify_all()


def _fr_others():
    ident = _fr_threading.get_ident()
    return sum(count for key, count in _FR_INFLIGHT.items() if key != ident)


def _fr_run_dir(owner):
    for attribute in ('run_dir', 'lifecycle_dir', 'directory'):
        value = getattr(owner, attribute, None)
        if isinstance(value, _FrPath):
            return value
        if isinstance(value, str) and value:
            return _FrPath(value)
    return None


def _fr_write(owner, name, payload):
    directory = _fr_run_dir(owner)
    if directory is None:
        return
    try:
        directory.mkdir(parents=True, exist_ok=True)
        (directory / name).write_text(
            _fr_json.dumps(payload, indent=2, ensure_ascii=False, default=str) + '\n',
            encoding='utf-8')
    except (OSError, TypeError, ValueError):
        pass


def quiesce_accepted_submissions(owner=None, reason='freeze'):
    """Wait for accepted submissions still being evaluated in other threads."""
    cap = _fr_cap()
    started = _fr_time.monotonic()
    with _FR_CV:
        entered = _fr_others()
        while _fr_others() > 0:
            remaining = cap - (_fr_time.monotonic() - started)
            if remaining <= 0:
                break
            _FR_CV.wait(min(5.0, remaining))
        outstanding = _fr_others()
    receipt = {
        'schema_version': 'agentswe-submission-quiesce/v1',
        'reason': reason,
        'inflight_at_entry': entered,
        'inflight_at_exit': outstanding,
        'quiesced': outstanding == 0,
        'waited_seconds': round(_fr_time.monotonic() - started, 3),
        'cap_seconds': cap,
    }
    if entered:
        _fr_write(owner, 'submission_quiesce.json', receipt)
    return receipt


def _fr_sealed(owner):
    if getattr(owner, 'frozen', None):
        return True
    if getattr(owner, 'freeze_manifest', None):
        return True
    directory = _fr_run_dir(owner)
    try:
        return bool(directory is not None and (directory / 'freeze_manifest.json').exists())
    except OSError:
        return False


def post_freeze_superseded(owner, record):
    """True when this evaluation finished after the seal: archive, never accept."""
    if not _fr_sealed(owner):
        return False
    if isinstance(record, dict):
        record['consumed'] = False
        record['submission_consumed'] = False
        record['consumes_capability_round'] = False
        record['retry_same_round'] = False
        record['retry_allowed'] = False
        record['post_freeze_superseded'] = True
        record['non_consuming_reason'] = 'post_freeze_completion'
    directory = _fr_run_dir(owner)
    if directory is not None:
        try:
            archive = directory / 'post_freeze_attempts'
            archive.mkdir(parents=True, exist_ok=True)
            index = len(list(archive.glob('attempt_*.json'))) + 1
            payload = record if isinstance(record, dict) else {'record': repr(record)}
            (archive / ('attempt_%03d.json' % index)).write_text(
                _fr_json.dumps(payload, indent=2, ensure_ascii=False, default=str) + '\n',
                encoding='utf-8')
        except (OSError, TypeError, ValueError):
            pass
    return True


def _fr_wrap_submit(cls, name='submit'):
    original = getattr(cls, name, None)
    if not _fr_inspect.isfunction(original) or getattr(original, '_fr_inflight', False):
        return False

    @_fr_functools.wraps(original)
    def wrapper(self, *args, **kwargs):
        _fr_begin()
        try:
            return original(self, *args, **kwargs)
        finally:
            _fr_end()

    wrapper._fr_inflight = True
    setattr(cls, name, wrapper)
    return True


def _fr_wrap_freeze(cls, name):
    original = getattr(cls, name, None)
    if not _fr_inspect.isfunction(original) or getattr(original, '_fr_quiesce', False):
        return False

    @_fr_functools.wraps(original)
    def wrapper(self, *args, **kwargs):
        quiesce_accepted_submissions(self, reason=name)
        return original(self, *args, **kwargs)

    wrapper._fr_quiesce = True
    setattr(cls, name, wrapper)
    return True


_fr_wrap_submit(Controller)
_FR_WRAPPED_FREEZE = [name for name in _FR_FREEZE_METHODS if _fr_wrap_freeze(Controller, name)]
assert _FR_WRAPPED_FREEZE, 'freeze/submit race guard found no freeze entry point'
# --- end 0921b freeze/submit race guard ------------------------------------


if __name__ == "__main__":
    raise SystemExit(main())
