"""Editing Builder model switch, applied to a rendered Editing install at setup time.

The paper's Editing control plane and the ten task trees name the upper Builder model (Codex harness) as literals
(deepseek-flash, effort max) in provider TOML, broker locks, receipts, attestations and gates. The paper switched
Builder models with tools/patch_builder_model.py: exact-anchor, Builder-only edits; the lower agent and the judges
keep their own models. This module ports those rules so that AGENTSWE_EDITING_BUILDER_MODEL (or
AGENTSWE_BUILDER_MODEL) and its effort reach every Builder-only site of a rendered install:

  * every rule is an exact anchor with an expected count; a rule whose replacement is already in place is skipped
    (idempotent: the control plane is re-rendered on every setup, task trees only when they change);
  * the canonical trees already carry the paper tool's split in some files (a BUILDER_MODEL constant next to the
    lower agent's MODEL); there the constant's value is switched and the split rules are dropped;
  * the Codex model catalog is generated by builders/codex/gen_codex_config.py for the Builder model (an entry with
    apply_patch freeform and multi_agent_version null; builder_segments adds [features] multi_agent = false to every
    provider TOML), and builder_segments.LITE_MODEL_CATALOG_SHA256 is pinned to the generated bytes;
  * the readiness preflight record (tools/launch_readiness.py) names the Builder model and effort.

Nothing is written unless every anchor of the plan matches (all-or-nothing). For the default Builder
(deepseek-flash, max) the plan is empty and the install keeps the paper bytes.
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import py_compile
import re
from pathlib import Path

DEFAULT_MODEL, DEFAULT_EFFORT = "deepseek-flash", "max"
TREE_KEYS = {
    "claude": "claude-policy-provenance", "aider": "aider-worktree-transaction",
    "openhands": "openhands-effect-recovery", "openclaw": "openclaw-channel-handoff",
    "codex": "codex-execution-residual", "ai": "ai-scientist-reproducibility-gate",
    "deepcode": "deepcode-claim-traceability", "deeptutor": "deeptutor-adaptive-remediation",
    "dyad": "dyad-acceptance-driven", "openwiki": "openwiki-change-impact",
}
EFFORTS = ("max", "xhigh", "high", "medium", "low")


class SwitchError(RuntimeError):
    pass


def _rules(model: str, effort: str, control: Path, tools: Path, trees: dict[str, Path]) -> dict[Path, list[tuple]]:
    """Port of the paper tool's plan() (model) plus the effort literal on the same Builder-only anchors."""
    OLD = DEFAULT_MODEL
    E: dict[Path, list[tuple]] = {}

    def add(path, *rules):
        E.setdefault(Path(path), []).extend(rules)

    def eff(text: str) -> str:
        """Builder effort literal next to the Builder model in an anchor's replacement."""
        if effort == DEFAULT_EFFORT:
            return text
        return (text.replace("'max'", f"'{effort}'").replace('"max"', f'"{effort}"')
                .replace("/xhigh", "/xhigh"))  # broker docstrings say /xhigh in the paper; left as written

    def sub(old_text: str, note: str, count: int = 1):
        return (old_text, eff(old_text.replace(OLD, model)), count, note)

    toml_old = r'\nmodel="%s"\n' % OLD  # inside a Python string literal: backslash-n, not a newline
    ctx_old = "any(v.get('model') != '%s' or v.get('effort') != 'max' for v in contexts)" % OLD
    nat_old = "'native_model': '%s', 'native_effort': 'max'," % OLD
    ident_old = "'provider_base_url':base_url,'model':'%s','reasoning_effort':'max'," % OLD

    def builder_toml(path):
        add(path, (toml_old, r'\nmodel="%s"\n' % model, 1, 'provider TOML model= (Builder container)'))

    def builder_ctx(path):
        add(path, sub(ctx_old, 'native Builder turn_context model and effort check'))

    def builder_native_runner(path):
        add(path, sub(nat_old, 'builder_transport.json native_model'))

    def builder_identity(path):
        add(path, sub(ident_old, 'builder_direct native identity receipt'))

    def builder_constant(path, quote='"', suffix=""):
        """A tree or control file that already carries a dedicated BUILDER_MODEL constant."""
        add(path, ('BUILDER_MODEL = %s%s%s%s' % (quote, OLD, quote, suffix),
                   'BUILDER_MODEL = %s%s%s%s' % (quote, model, quote, suffix), 1, 'Builder-only constant'))

    def builder_effort_constant(path):
        if effort != DEFAULT_EFFORT:
            add(path, ('BUILDER_EFFORT = "max"', 'BUILDER_EFFORT = "%s"' % effort, 1, 'Builder-only effort constant'))

    # ---- shared control plane ---------------------------------------------------------------------------------
    builder_toml(control / 'direct_harbor_builder.py')
    builder_constant(control / 'readiness_binding.py', quote="'", suffix="  # upper Builder provider-TOML model")
    add(control / 'test_readiness_binding.py', (toml_old, r'\nmodel="%s"\n' % model, 2, 'provider-TOML fixtures'))
    add(control / 'builder_broker_xhigh.py',
        ('"""Evaluator-owned Responses broker locked to %s/xhigh.' % OLD,
         '"""Evaluator-owned Responses broker locked to %s/xhigh.' % model, 1, 'Builder-only broker docstring'),
        sub('MODEL = "%s"\nEFFORT = "max"' % OLD, 'Builder-only broker model and effort'))
    add(control / 'responses_broker_xhigh.py',
        ('"""Builder-only Responses broker locked to %s/xhigh."""' % OLD,
         '"""Builder-only Responses broker locked to %s/xhigh."""' % model, 1, 'Builder-only broker docstring'),
        ('MODEL = "%s"\nMAX_BODY' % OLD, 'MODEL = "%s"\nMAX_BODY' % model, 1, 'Builder-only broker model'))
    add(control / 'builder_broker_runtime.py',
        sub("health.get('model')=='%s' and health.get('reasoning_effort')=='max'" % OLD, 'Builder broker healthz gate'))
    for name in ('formal_config.py', 'validate_formal_config.py'):
        add(control / name, sub('"builder_model": "%s",\n        "builder_reasoning_effort": "max",' % OLD,
                                'codex_xhigh profile builder_model'))
    add(control / 'build_create_alignment_snapshot.py',
        sub('"builder_model": "%s",\n            "builder_reasoning_effort": "max",' % OLD,
            'Create-alignment snapshot builder_model'))
    add(control / 'v2_readiness.py',
        sub('require(native.get("model") == "%s" and native.get("effort") == "max"' % OLD, 'builder_native receipt gate'))
    add(control / 'v2_test_fixtures.py',
        sub('model="%s", effort="max", state="terminal", thread_ids=["builder-thread"]' % OLD,
            'builder_native receipt fixture'))
    add(tools / 'launch_readiness.py',
        sub("'builder_model': '%s', 'builder_reasoning_effort': 'max'," % OLD, 'readiness preflight record'))

    # ---- task trees --------------------------------------------------------------------------------------------
    T = trees['claude']
    builder_constant(T / 'agentloop/evaluator/builder_protocol.py')
    add(T / 'agentloop/protocol_lock.json',
        ('"builder": {"model": "%s", "reasoning_effort": "xhigh"' % OLD,
         '"builder": {"model": "%s", "reasoning_effort": "xhigh"' % model, 1, 'checked-in builder lock'))
    add(T / 'evaluator/readiness_bundle.py',
        ('attestation.get("builder_model") == "%s"' % OLD, 'attestation.get("builder_model") == "%s"' % model, 1,
         'Builder attestation gate'),
        sub('builder_session_id=session, model="%s", effort="max",' % OLD, 'builder_native receipt'))
    add(T / 'evaluator/formal_finalize.py',
        ('session.get("builder_model") != "%s"' % OLD, 'session.get("builder_model") != "%s"' % model, 1,
         'formal Builder lock gate'))
    builder_toml(T / 'harbor/direct_harbor_builder.py')
    builder_ctx(T / 'harbor/native_builder_evidence.py')
    builder_identity(T / 'harbor/builder_direct.py')
    add(T / 'harbor/builder_broker.py',
        ('"""Evaluator-owned Responses broker locked to %s/xhigh.' % OLD,
         '"""Evaluator-owned Responses broker locked to %s/xhigh.' % model, 1, 'Builder-only broker docstring'),
        sub('MODEL = "%s"\nEFFORT = "max"' % OLD, 'Builder-only broker model and effort'))
    add(T / 'harbor/formal_one_stop.py',
        ('%s/xhigh, one public lower broker locked to %s/medium' % (OLD, OLD),
         '%s/xhigh, one public lower broker locked to %s/medium' % (model, OLD), 1, 'module docstring, Builder half'),
        ('You are one uninterrupted %s/xhigh Builder session.' % OLD,
         'You are one uninterrupted %s/xhigh Builder session.' % model, 1, 'Builder instruction prompt'))

    for key in ('aider', 'openhands', 'openclaw', 'codex', 'ai', 'deepcode'):
        T = trees[key]
        # the canonical trees carry the paper tool's split: BUILDER_MODEL next to the lower agent's MODEL
        builder_constant(T / ('evaluator/formal_gates.py' if key == 'openclaw' else 'harbor/formal_one_stop.py'),
                         suffix="  # upper Builder (Codex harness) only")
        builder_effort_constant(T / 'harbor/formal_one_stop.py')
        if key != 'openhands':
            builder_toml(T / 'harbor/direct_harbor_builder.py')
        builder_ctx(T / 'harbor/native_builder_evidence.py')
    for key in ('aider', 'codex', 'ai', 'deepcode', 'openclaw', 'openhands'):
        T = trees[key]
        receipt = {
            'aider': "builder_session_id=session, model='%s'," % OLD,
            'codex': "builder_session_id=session, model='%s'," % OLD,
            'ai': "builder_session_id=session,model='%s',effort='max'" % OLD,
            'deepcode': "model='%s', effort='max', state='terminal', thread_ids=[session]," % OLD,
            'openclaw': "model='%s', effort='max', state='terminal', thread_ids=[session]," % OLD,
            'openhands': 'model="%s", effort="max", state="terminal", thread_ids=[session],' % OLD,
        }[key]
        add(T / 'evaluator/readiness_bundle.py', sub(receipt, 'builder_native receipt'))
    for key in ('aider', 'codex'):
        builder_identity(trees[key] / 'harbor/builder_direct.py')
    for key in ('openclaw', 'ai', 'deepcode'):
        builder_native_runner(trees[key] / 'harbor/native_builder_runner.py')
    T = trees['openhands']
    add(T / 'evaluator/schemas/builder_broker_stats.schema.json',
        ('"model": {"const": "%s"}' % OLD, '"model": {"const": "%s"}' % model, 2, 'Builder broker stats schema'))
    add(T / 'evaluator/schemas/protocol_lock.json',
        ('"builder": {"product": "Codex", "model": "%s"' % OLD, '"builder": {"product": "Codex", "model": "%s"' % model,
         1, 'checked-in builder lock'))
    add(T / 'harbor/readiness_contract.py', sub('MODEL = "%s"\nEFFORT = "max"' % OLD, 'Builder-only readiness lock'))
    T = trees['openclaw']
    add(T / 'controller/builder_session_controller.py',
        sub('"builder_model": "%s", "builder_reasoning_effort": "max",' % OLD, 'Builder session attestation'))
    add(T / 'infra/self_test.py',
        ('lock["builder_model"]=="%s"' % OLD, 'lock["builder_model"]=="%s"' % model, 1, 'self-test builder lock'))
    add(T / 'harbor/formal_one_stop.py',
        ('You are the single upper Builder. Use %s with xhigh reasoning. Read' % OLD,
         'You are the single upper Builder. Use %s with xhigh reasoning. Read' % model, 1, 'Builder instruction prompt'))
    T = trees['codex']
    add(T / 'harbor/responses_broker_xhigh.py',
        ('"""Builder-only Responses broker locked to %s/xhigh."""' % OLD,
         '"""Builder-only Responses broker locked to %s/xhigh."""' % model, 1, 'Builder-only broker docstring'),
        ('MODEL = "%s"\nMAX_BODY' % OLD, 'MODEL = "%s"\nMAX_BODY' % model, 1, 'Builder-only broker model'))
    add(T / 'harbor/readiness_launcher.py',
        sub("'builder': {'model': '%s', 'effort': 'max', 'single_uninterrupted_turn': True}" % OLD,
            'readiness protocol_lock builder entry'))
    add(T / 'harbor/formal_one_stop.py',
        ('The Builder is a single Harbor Codex session using %s/xhigh.' % OLD,
         'The Builder is a single Harbor Codex session using %s/xhigh.' % model, 1, 'module docstring'),
        ('Your harness/model is Codex with %s and xhigh reasoning.' % OLD,
         'Your harness/model is Codex with %s and xhigh reasoning.' % model, 1, 'Builder instruction prompt'))
    T = trees['deepcode']
    add(T / 'harbor/formal_one_stop.py',
        ('    one %s/xhigh Builder session\n' % OLD, '    one %s/xhigh Builder session\n' % model, 1, 'module docstring'),
        ('help="independently validated %s/xhigh Builder broker",' % OLD,
         'help="independently validated %s/xhigh Builder broker",' % model, 1, '--builder-broker-script help'))
    T = trees['deeptutor']
    builder_constant(T / 'agentloop/protocol.py')
    add(T / 'agentloop/protocol_lock.json',
        ('"builder_model": "%s",' % OLD, '"builder_model": "%s",' % model, 1, 'checked-in builder lock'))
    add(T / 'evaluator/readiness_bundle.py',
        sub("model='%s', effort='max', state='terminal', thread_ids=[session]," % OLD, 'builder_native receipt'))
    builder_toml(T / 'harbor/direct_harbor_builder.py')
    builder_ctx(T / 'harbor/native_builder_evidence.py')
    builder_native_runner(T / 'harbor/native_builder_runner.py')
    add(T / 'harbor/formal_one_stop.py',
        ('One Harbor Builder process owns one continuous %s/xhigh session.' % OLD,
         'One Harbor Builder process owns one continuous %s/xhigh session.' % model, 1, 'module docstring'),
        ('        and BUILDER_MODEL == LOWER_MODEL == "%s"\n' % OLD, '        and LOWER_MODEL == "%s"\n' % OLD, 1,
         'self-test: the Builder model no longer has to equal the lower model'))
    T = trees['dyad']
    add(T / 'evaluator/readiness_bundle.py',
        sub("model='%s', effort='max', state='terminal', thread_ids=[session]," % OLD, 'builder_native receipt'))
    builder_toml(T / 'harbor/direct_harbor_builder.py')
    builder_ctx(T / 'harbor/native_builder_evidence.py')
    builder_native_runner(T / 'harbor/native_builder_runner.py')
    add(T / 'harbor/builder_broker.py',
        ('"""Evaluator-owned Builder broker locked to %s/xhigh.' % OLD,
         '"""Evaluator-owned Builder broker locked to %s/xhigh.' % model, 1, 'Builder-only broker docstring'),
        sub('MODEL = "%s"\nEFFORT = "max"' % OLD, 'Builder-only broker model and effort'))
    builder_constant(T / 'harbor/builder_protocol.py')
    add(T / 'harbor/formal_one_stop.py',
        ('            assert BUILDER_MODEL == LOWER_MODEL == "%s"\n' % OLD, '            assert LOWER_MODEL == "%s"\n' % OLD,
         1, 'self-test: the Builder model no longer has to equal the lower model'))
    T = trees['openwiki']
    builder_constant(T / 'agentloop/protocol.py')
    add(T / 'evaluator/readiness_bundle.py',
        sub("model='%s', effort='max', state='terminal', thread_ids=[session]," % OLD, 'builder_native receipt'))
    builder_ctx(T / 'harbor/native_builder_evidence.py')
    return E


def _load_generator(repo: Path):
    spec = importlib.util.spec_from_file_location("agentswe_gen_codex_config", repo / "builders/codex/gen_codex_config.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def plan(model: str, effort: str, root: Path, repo: Path, context_window: int | None = None) -> dict:
    """All edits for a rendered Editing install at `root` (<home>/editing): {path: new text}, plus a report."""
    if effort not in EFFORTS:
        raise SwitchError(f"Editing Builder effort {effort!r}: expected one of {', '.join(EFFORTS)}")
    trees = {k: root / "tasks" / tid / "tree" for k, tid in TREE_KEYS.items()}
    control, tools = root / "control", root / "tools"
    report: dict = {"model": model, "effort": effort, "edits": [], "already": [], "problems": []}
    out: dict[Path, str] = {}
    if (model, effort) == (DEFAULT_MODEL, DEFAULT_EFFORT):
        return {"files": out, "report": report}
    for path, rules in sorted(_rules(model, effort, control, tools, trees).items(), key=lambda kv: str(kv[0])):
        if not path.is_file():
            report["problems"].append(f"missing {path.relative_to(root)}")
            continue
        text = path.read_text(encoding="utf-8")
        new = text
        for old, rep, count, note in rules:
            if old == rep:
                continue
            found = new.count(old)
            if found == count:
                new = new.replace(old, rep)
                report["edits"].append(f"{path.relative_to(root)}: {note}")
            elif found == 0 and new.count(rep) >= count:
                report["already"].append(f"{path.relative_to(root)}: {note}")
            else:
                report["problems"].append(f"{path.relative_to(root)}: anchor found {found}x, expected {count}: {note}")
        if new != text:
            out[path] = new
    # Codex catalog for the Builder model, generated, and its pin in builder_segments
    gen = _load_generator(repo)
    base = json.loads((repo / "builders/codex/catalog/codex-0.144.1-lite-v1.json").read_text())
    known = json.loads((repo / "builders/codex/known_models.json").read_text())
    try:
        catalog, notes = gen.build_catalog(model, base_catalog=base, known=known, context_window=context_window)
    except gen.GenerationError as exc:
        raise SwitchError(f"Codex catalog for {model!r}: {exc}") from exc
    blob = gen.dump_catalog(catalog)
    cat = control / "codex_model_catalog_lite.json"
    if not cat.is_file() or cat.read_text(encoding="utf-8") != blob:
        out[cat] = blob
        report["edits"].append(f"control/codex_model_catalog_lite.json: catalog for {model} ({notes})")
    seg = control / "builder_segments.py"
    pin = hashlib.sha256(blob.encode()).hexdigest()
    seg_text = out.get(seg) or seg.read_text(encoding="utf-8")
    new_seg, k = re.subn(r'(?m)^LITE_MODEL_CATALOG_SHA256 = "[0-9a-f]{64}"$', f'LITE_MODEL_CATALOG_SHA256 = "{pin}"',
                         seg_text)
    if k != 1:
        report["problems"].append("control/builder_segments.py: LITE_MODEL_CATALOG_SHA256 pin not found exactly once")
    elif new_seg != seg_text:
        out[seg] = new_seg
        report["edits"].append(f"control/builder_segments.py: catalog pin {pin[:12]}")
    report["catalog_sha256"] = pin
    return {"files": out, "report": report}


def apply(model: str, effort: str, root: Path, repo: Path, context_window: int | None = None) -> dict:
    """Write every planned edit, or nothing (raises SwitchError listing every problem)."""
    result = plan(model, effort, root, repo, context_window)
    report = result["report"]
    if report["problems"]:
        raise SwitchError("Editing Builder switch refused; no file was changed:\n  " + "\n  ".join(report["problems"]))
    for path, text in result["files"].items():
        path.write_text(text, encoding="utf-8")
        if path.suffix == ".py":
            py_compile.compile(str(path), doraise=True)
        elif path.suffix == ".json":
            json.loads(text)
    return report
