"""Baseline-locked, complete-change Code inputs for the actual Aider product."""
from __future__ import annotations

import ast
import hashlib
import json
import os
import runpy
import sys
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from harbor.agentloop_controller import digest as native_digest

CREATE = Path('@@AGENTSWE_EDITING_CONTROL@@/code_eval.py')
SHARED = Path('@@AGENTSWE_EDITING_CONTROL@@/formal_axes_shared.py')
BASELINE_DIGEST = '1787cfbc6c4c79c4b918f7cd155d6274204651bbdddfc6689bac83c674e13575'


@lru_cache(maxsize=1)
def packer():
    return runpy.run_path(str(CREATE), run_name='aider_code_input_packer')


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def immutable(path, value):
    data = (json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False) + '\n').encode()
    if path.is_symlink():
        raise ValueError('Code evidence may not be a symlink')
    if path.exists():
        if path.read_bytes() != data:
            raise ValueError('Code inputs changed; use a new scoring directory: ' + str(path))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('xb') as stream:
        stream.write(data)


def inventory(root):
    value = {}
    for path in sorted(root.rglob('*')):
        rel = path.relative_to(root).as_posix()
        if path.is_symlink():
            value[rel] = {'kind': 'symlink', 'target': os.readlink(path)}
        elif path.is_file():
            value[rel] = {'kind': 'file', 'sha256': sha(path), 'bytes': path.stat().st_size}
    return value


def is_cache(path):
    return '__pycache__' in Path(path).parts or path.endswith('.pyc')


def local_imports(source, selected, files):
    pending = list(selected)
    selected = set(selected)
    while pending:
        rel = pending.pop()
        if not rel.endswith('.py') or files[rel]['kind'] != 'file':
            continue
        try:
            tree = ast.parse((source / rel).read_text(), filename=rel)
        except (SyntaxError, UnicodeError):
            continue  # Bad Candidate syntax remains included, not silently repaired.
        package = rel[:-3].split('/')[:-1]
        modules = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                modules.update(alias.name for alias in node.names)
            elif isinstance(node, ast.ImportFrom):
                prefix = package[:len(package) - node.level + 1] if node.level else []
                module = '.'.join(prefix + ([node.module] if node.module else []))
                modules.add(module)
                modules.update(module + '.' + alias.name for alias in node.names if alias.name != '*')
        for module in modules:
            parts = module.split('.')
            for index in range(1, len(parts) + 1):
                raw = '/'.join(parts[:index])
                for path in (raw + '.py', raw + '/__init__.py'):
                    if path in files and path not in selected:
                        selected.add(path)
                        pending.append(path)
    return selected


def build_scope(source, code_digest, output, *, baseline=None, expected_baseline=BASELINE_DIGEST):
    baseline = baseline or ROOT / 'input/repository'
    create = packer()
    observed = create['tree_digest'](baseline)
    if observed != expected_baseline or create['tree_digest'](source) != code_digest:
        raise ValueError('baseline or frozen product identity mismatch')
    old, new = inventory(baseline), inventory(source)
    added, deleted = sorted(new.keys() - old.keys()), sorted(old.keys() - new.keys())
    changed = sorted(path for path in new.keys() & old.keys() if new[path] != old[path])
    caches = sorted(path for path in added + changed if is_cache(path))
    build = json.loads((source / 'build_result.json').read_text())
    declared = build.get('changed_paths')
    if not isinstance(declared, list) or any(is_cache(path) for path in declared):
        raise ValueError('Candidate-edited cache bytes cannot be excluded from Code evidence')
    if build.get('classification') != 'ready_for_lower':
        raise ValueError('frozen source lacks evaluator materializer compilation evidence')
    # Only the trusted materializer's generated bytecode is excluded. .git and
    # every other actual change remain mandatory; unexpected skips fail closed.
    mandatory = set(added + changed) - set(caches)
    seeds = mandatory | {path for path in new if not is_cache(path) and (
        (path.startswith('aider/') and not path.startswith('aider/website/'))
        or path in {'pyproject.toml', 'setup.py', 'requirements.txt', 'README.md', 'AGENTS.md'}
        or path.startswith('requirements/'))}
    selected = local_imports(source, seeds, new)
    selected = {path for path in selected if not is_cache(path)}
    manifest, text = create['source_manifest_and_pack'](source,
        max_pack_bytes=create['MAX_SOURCE_PACK_BYTES'], evidence_paths=sorted(selected))
    included = {entry['path'] for entry in manifest['files'] if entry.get('included_in_evidence_pack')}
    missing = sorted(mandatory - included)
    scope = {'schema_version': 'agentswe-edit-code-scope/v1', 'candidate_digest': code_digest,
        'baseline_path': str(baseline), 'baseline_expected_digest': expected_baseline,
        'baseline_observed_digest': observed, 'complete_change_coverage': not missing,
        'valid': not missing and manifest['tree_digest'] == code_digest,
        'errors': [{'changed_content_not_in_context': missing}] if missing else [],
        'evidence_paths': sorted(selected), 'changed_paths': [p for p in changed if p not in caches],
        'added_paths': [p for p in added if p not in caches], 'deleted_paths': deleted,
        'dependency_paths': sorted(selected - seeds), 'mandatory_included_paths': sorted(mandatory & included),
        'mandatory_excluded_paths': missing, 'source_manifest_tree_digest': manifest['tree_digest'],
        'estimated_pack_bytes': len(text.encode()), 'evidence_pack_sha256': hashlib.sha256(text.encode()).hexdigest(),
        'selection_policy': 'All non-generated changes, all Aider production implementation/configuration, changed tests, recursive static local imports; unchanged website/history fixtures excluded.',
        'scope_basis': {'public_requirement_basis': {p.name: sha(p) for p in sorted((ROOT / 'input').glob('*.md'))}},
        'scope_case_policy': 'Task-wide public interface and all 2 dev/6 hidden mechanisms, never a case-specific favorable subset.',
        'evaluator_generated_metadata_exclusions': [{'path': path, **new[path],
            'reason': 'trusted evaluator py_compile output; not present in materializer changed_paths',
            'materializer_record_sha256': sha(source / 'build_result.json')} for path in caches],
        'unchanged_dependency_pack_exclusions': [{'path': path, **new[path],
            'reason': 'unchanged website/history/other non-production context; all production Aider files and actual changes included'}
            for path in sorted(new.keys() - selected - set(caches))],
        'changed_file_evidence': {path: {'before': old.get(path), 'after': new.get(path)} for path in sorted(mandatory)},
        'deleted_file_evidence': {path: old[path] for path in deleted},
        'dependency_resolution': 'Static local Python imports. Dynamic imports are not claimed complete; complete Aider production tree is explicitly included.'}
    if create['tree_digest'](source) != code_digest or create['tree_digest'](baseline) != expected_baseline:
        raise ValueError('source changed during Code scope preparation')
    scope['manifest_path'] = str(output / 'code_evidence_scope.json')
    immutable(Path(scope['manifest_path']), scope)
    if not scope['valid']:
        raise ValueError('Code source scope has uncovered Candidate changes')
    return scope


def prepare_code_inputs(run_dir, frozen):
    source = Path(frozen['frozen_candidate_path']).resolve()
    native = frozen['candidate_digest']
    if native_digest(source) != native:
        raise ValueError('native frozen Candidate digest mismatch before Code preparation')
    full = packer()['tree_digest'](source)
    output = run_dir / 'formal_scoring/code_inputs'
    scope = build_scope(source, full, output)
    shared = runpy.run_path(str(SHARED), run_name='aider_code_scope_validator')
    paths = shared['checked_code_scope'](scope, source, full)
    requirements = run_dir / 'formal_scoring/code_public_requirements'
    requirements.mkdir(parents=True, exist_ok=True)
    public = {path.name: path.read_bytes() for path in sorted((ROOT / 'input').glob('*.md'))}
    public['90_evaluator_code_scope_context.md'] = shared['code_scope_context_text'](scope).encode()
    for name, data in public.items():
        target = requirements / name
        if target.is_symlink() or (target.exists() and target.read_bytes() != data):
            raise ValueError('Code public requirements changed; new output required')
        if not target.exists():
            with target.open('xb') as stream:
                stream.write(data)
    binding = {'candidate_source': str(source), 'task_candidate_digest': native,
        'code_full_tree_digest': full, 'source_projection': False, 'scope': scope['manifest_path'],
        'public_requirements_digest': packer()['tree_digest'](requirements),
        'native_digest_implementation_sha256': sha(ROOT / 'harbor/agentloop_controller.py'),
        'Create_digest_implementation_sha256': sha(CREATE), 'adapter_sha256': sha(Path(__file__)),
        'scope_policy': 'all public task mechanisms + complete Candidate changes, never Result evidence'}
    immutable(output / 'code_source_binding.json', binding)
    return source, requirements, full, paths
