#!/usr/bin/env python3
"""Minimal negative-control hook; not a task reference implementation."""
import hashlib, hmac, json, os, sys
data=json.load(sys.stdin); session=str(data.get("session_id","unknown")); event=str(data.get("tool_use_id","unknown")); tool=str(data.get("tool_name","unknown")); kind=str(data.get("hook_event_name","PreToolUse"))
identity=(session+"\0"+event).encode(); receipt_id="pol_"+hashlib.sha256(identity).hexdigest()[:24]; digest="sha256:"+hashlib.sha256(json.dumps(data.get("tool_input",{}),sort_keys=True,separators=(",",":")).encode()).hexdigest(); integrity="hmac-sha256:"+hmac.new(b"selftest-only",identity+digest.encode(),hashlib.sha256).hexdigest()
receipt={"schema_version":1,"receipt_id":receipt_id,"session_id":session,"event_id":event,"tool_name":tool,"decision":"deny","policy_id":"legacy","policy_epoch":0,"policy_revision":"calibration","policy_snapshot_digest":"sha256:"+hashlib.sha256(b"calibration").hexdigest(),"canonical_action_digest":digest,"key_id":"key_"+hashlib.sha256(b"selftest-only").hexdigest()[:16],"ledger_sequence":1,"integrity":integrity,"delegation_id":None,"delegation_parent_id":None,"delegation_key_id":None,"delegation_scope_digest":None,"reservation_id":None,"reservation_state":"unlimited","quota_remaining":None,"approval_ticket_id":None,"approval_state":"not_required","approval_count":None,"approval_threshold":None,"approval_round":None,"approval_required_groups":[],"approval_satisfied_groups":[],"owner_instance_id":None,"owner_generation":None,"ownership_state":"unmanaged","handoff_id":None,"state_format_version":1,"upgrade_id":None,"upgrade_state":"stable","effect_id":None,"effect_generation":None,"effect_state":"not_configured","repair_id":None,"repair_generation":0,"integrity_state":"healthy","session_authority_id":None,"session_generation":None,"continuation_id":None,"continuation_state":"not_configured"}
state=os.environ.get("POLICY_PROVENANCE_STATE_DIR"); os.makedirs(state,exist_ok=True)
audit={"schema_version":1,"kind":"pre" if kind=="PreToolUse" else "post","sequence":1,**receipt,"summary":"calibration denied","previous_event_digest":"sha256:"+"0"*64}
audit["event_digest"]="sha256:"+hashlib.sha256(json.dumps(audit,sort_keys=True,separators=(",",":")).encode()).hexdigest()
with open(os.path.join(state,"audit.jsonl"),"a",encoding="utf-8") as stream: stream.write(json.dumps(audit,separators=(",",":"))+"\n")
print(json.dumps({"hookSpecificOutput":{"hookEventName":kind,"permissionDecision":"deny","permissionDecisionReason":"calibration denied","updatedInput":None},"policyReceipt":receipt},separators=(",",":")))
